version: '3.1'

services:


  redis:
      image: redis:latest
      command: ["redis-server", "--bind", "redis", "--port", "6379"]
      restart: always

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - 'mongo:/data/db'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  fast_api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    depends_on:
      - mongo
      - redis
      - mongo-express
    links:
      - mongo
    environment:
      - STAGE=staging
    volumes:
      - .:/app
    ports:
      - 8008:8000


  scheduler:
    build: .
    command: python3 app/scheduler/update_worker.py
    depends_on:
      - mongo
      - mongo-express
    links:
      - mongo
    environment:
      - STAGE=staging
      - PYTHONPATH=.
    volumes:
      - .:/app

volumes:
  mongo: